#!/bin/sh

# if $1 is empty exit
if [ -z "$1" ]; then
    echo "No file supplied"
    exit 1
fi

cd ~/.config/nvim/Resources/ || exit

sed -i "/\/\//d" "$1"
# python3 -m json.tool "$1" | sponge "$1" # install moreutils for sponge
python3 -m json.tool "$1" > ~/.cache/vsc2nvim_theme/"$1"
mv -f ~/.cache/vsc2nvim_theme/"$1" ./"$1"
./djanho -l "$1"
name="${1%.json}"
sed -i "3s;^;vim.g.colors_name = '$name'\n;" generated.lua
mv ./generated.lua ../after/colors/"$name".lua

