-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#28A9FF'
local Color0 = '#b7d175'
local Color14 = '#181818'
local Color2 = '#D62C2C'
local Color8 = '#A95EFF'
local Color16 = '#efd6d6'
local Color5 = '#a1a1a1'
local Color13 = '#f4f4f4'
local Color15 = '#ddf1e4'
local Color4 = '#ffaa18'
local Color17 = '#d6d6d6'
local Color18 = '#b8b8b8'
local Color19 = '#7e7e7e'
local Color9 = '#FF478D'
local Color6 = '#00d6c4'
local Color1 = '#8a8a8a'
local Color10 = '#FF7135'
local Color12 = '#414141'
local Color11 = '#ebebeb'
local Color7 = '#00d647'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color13, Color14, nil)
highlight('Pmenu', Color13, Color14, nil)
highlight('PmenuSel', Color14, Color13, nil)
highlight('PmenuThumb', Color13, Color14, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color13, Color14, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color19, Color13, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color14, nil)

link('TSFunction', 'Function')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('TSFloat', 'Number')
link('TSConditional', 'Conditional')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('NonText', 'Comment')
link('TSComment', 'Comment')
link('TSNumber', 'Number')
link('TSTagDelimiter', 'Type')
link('Folded', 'Comment')
link('Whitespace', 'Comment')
link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('Operator', 'Keyword')
link('Macro', 'Function')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TelescopeNormal', 'Normal')
link('TSNamespace', 'TSType')
link('TSField', 'Constant')
link('TSString', 'String')
link('TSPunctBracket', 'MyTag')
link('Conditional', 'Operator')
link('TSFuncMacro', 'Macro')
link('TSTag', 'MyTag')
link('TSKeyword', 'Keyword')
link('CursorLineNr', 'Identifier')
link('TSLabel', 'Type')
link('TSProperty', 'TSField')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSConstant', 'Constant')
