-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color10 = '#cde1e1'
local Color1 = '#bc6b79'
local Color8 = '#ffffff'
local Color9 = '#38363f'
local Color3 = '#6aa7a7'
local Color2 = '#bcae6b'
local Color4 = '#8d89a5'
local Color5 = '#c2bed6'
local Color6 = '#664e4d'
local Color7 = '#cf433e'
local Color0 = '#545263'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color8, Color4, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color8, nil)
highlight('TabLine', Color8, Color8, nil)
highlight('TabLineFill', Color8, Color8, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('Repeat', 'Conditional')
link('Macro', 'Function')
link('TSTagDelimiter', 'Type')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('NonText', 'Comment')
link('TSString', 'String')
link('TSNamespace', 'TSType')
link('TSRepeat', 'Repeat')
link('TSComment', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSProperty', 'TSField')
link('TSFuncMacro', 'Macro')
link('TSOperator', 'Operator')
link('Operator', 'Keyword')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSKeyword', 'Keyword')
link('TSTag', 'MyTag')
link('Conditional', 'Operator')
link('Folded', 'Comment')
link('TSParameter', 'Constant')
link('TSFunction', 'Function')
link('TSField', 'Constant')
link('TSNumber', 'Number')
link('CursorLineNr', 'Identifier')
link('TSFloat', 'Number')
link('TSType', 'Type')
link('TSLabel', 'Type')
link('TSConstant', 'Constant')
link('Whitespace', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TelescopeNormal', 'Normal')
link('TSConditional', 'Conditional')
