-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#ce1836'
local Color9 = '#e3e2e0'
local Color0 = '#777777'
local Color1 = '#3bc7b8'
local Color3 = '#edb92e'
local Color13 = '#2c2c2c'
local Color5 = '#664e4d'
local Color10 = '#222222'
local Color12 = '#555555'
local Color11 = '#6b3031'
local Color8 = '#ff4e50'
local Color6 = '#cf433e'
local Color4 = '#c3cb4c'
local Color14 = '#888888'
local Color7 = '#ffffff'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color1, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color1, nil)
highlight('Function', nil, Color4, nil)
highlight('Error', Color5, Color6, nil)
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color10, Color9, nil)
highlight('Pmenu', Color10, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color10, Color9, nil)
highlight('Normal', Color10, Color9, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color14, nil)
highlight('TabLineFill', Color13, Color14, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSConstant', 'Constant')
link('NonText', 'Comment')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSOperator', 'Operator')
link('TSNumber', 'Number')
link('Conditional', 'Operator')
link('Macro', 'Function')
link('TSString', 'String')
link('TSComment', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('TSTagDelimiter', 'Type')
link('TelescopeNormal', 'Normal')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSProperty', 'TSField')
link('Operator', 'Keyword')
link('TSFunction', 'Function')
link('TSType', 'Type')
link('Whitespace', 'Comment')
link('TSTag', 'MyTag')
link('TSConditional', 'Conditional')
link('TSPunctBracket', 'MyTag')
link('TSFuncMacro', 'Macro')
link('TSLabel', 'Type')
link('TSFloat', 'Number')
link('TSNamespace', 'TSType')
