-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#88c448'
local Color12 = '#561d2d'
local Color3 = '#ee4266'
local Color1 = '#a2d66b'
local Color0 = '#4c4c70'
local Color11 = '#9090b2'
local Color7 = '#cf433e'
local Color5 = '#ffd23f'
local Color9 = '#9d50ba'
local Color6 = '#664e4d'
local Color10 = '#0b0b11'
local Color14 = '#13131d'
local Color4 = '#f3fcf0'
local Color8 = '#ffffff'
local Color13 = '#33334f'
local Color15 = '#5b5b8d'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color8, Color9, nil)
highlight('WildMenu', Color10, Color11, nil)
highlight('Pmenu', Color10, Color11, nil)
highlight('PmenuSel', Color11, nil, nil)
highlight('PmenuThumb', Color10, Color11, nil)
highlight('Normal', Color10, Color11, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color14, Color15, nil)
highlight('TabLineFill', Color14, Color15, nil)
highlight('TSPunctDelimiter', nil, Color11, nil)

link('TSTag', 'MyTag')
link('Macro', 'Function')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('Operator', 'Keyword')
link('CursorLineNr', 'Identifier')
link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSString', 'String')
link('TSTagDelimiter', 'Type')
link('TSPunctBracket', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSConstant', 'Constant')
link('NonText', 'Comment')
link('TSParameter', 'Constant')
link('Folded', 'Comment')
link('TSNumber', 'Number')
link('TSConditional', 'Conditional')
link('TSFunction', 'Function')
link('TSNamespace', 'TSType')
link('TSType', 'Type')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TSFloat', 'Number')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameterReference', 'TSParameter')
link('TSProperty', 'TSField')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('Whitespace', 'Comment')
link('TSFuncMacro', 'Macro')
