-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#88c448'
local Color3 = '#a0afa1'
local Color1 = '#a2d66b'
local Color4 = '#8c9191'
local Color5 = '#664e4d'
local Color7 = '#6c8375'
local Color0 = '#b1c9c9'
local Color6 = '#cf433e'
local Color9 = '#4d5151'
local Color10 = '#ecf6e1'
local Color12 = '#b3b7b7'
local Color8 = '#ffffff'
local Color11 = '#cccccc'
local Color13 = '#f5f5f5'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color4, nil)
highlight('Error', Color5, Color6, nil)
highlight('StatusLine', Color8, Color7, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color11, nil)
highlight('TabLine', Color13, Color12, nil)
highlight('TabLineSel', Color9, nil, nil)
highlight('TabLineFill', Color13, Color12, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('Whitespace', 'Comment')
link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
link('TSParameter', 'Constant')
link('TSString', 'String')
link('Macro', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSRepeat', 'Repeat')
link('Operator', 'Keyword')
link('NonText', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSPunctBracket', 'MyTag')
link('TSKeyword', 'Keyword')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSField', 'Constant')
link('TSType', 'Type')
link('TSFunction', 'Function')
link('TSConditional', 'Conditional')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSOperator', 'Operator')
link('TSProperty', 'TSField')
link('Folded', 'Comment')
link('TSNumber', 'Number')
link('TSLabel', 'Type')
link('TSConstant', 'Constant')
link('Conditional', 'Operator')
link('CursorLineNr', 'Identifier')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
