-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color4 = '#cbdad5'
local Color0 = '#6c6c87'
local Color9 = '#ebebf4'
local Color11 = '#6a6a85'
local Color13 = '#464657'
local Color2 = '#89a7b1'
local Color6 = '#cf433e'
local Color5 = '#664e4d'
local Color12 = '#a1a1b4'
local Color3 = '#566981'
local Color8 = '#3d3d4c'
local Color1 = '#9eb2d9'
local Color10 = '#454b5d'
local Color7 = '#ffffff'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color4, nil)
highlight('Error', Color5, Color6, nil)
highlight('StatusLine', Color7, Color3, nil)
highlight('WildMenu', Color8, Color9, nil)
highlight('Pmenu', Color8, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color8, Color9, nil)
highlight('Normal', Color8, Color9, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color11, nil)
highlight('TabLine', Color13, Color12, nil)
highlight('TabLineFill', Color13, Color12, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSFloat', 'Number')
link('TSLabel', 'Type')
link('TSFuncMacro', 'Macro')
link('TelescopeNormal', 'Normal')
link('TSParameterReference', 'TSParameter')
link('TSField', 'Constant')
link('Folded', 'Comment')
link('TSParameter', 'Constant')
link('Operator', 'Keyword')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Conditional', 'Operator')
link('Macro', 'Function')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSKeyword', 'Keyword')
link('Repeat', 'Conditional')
link('TSComment', 'Comment')
link('TSConstant', 'Constant')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('TSProperty', 'TSField')
link('CursorLineNr', 'Identifier')
link('TSRepeat', 'Repeat')
link('Whitespace', 'Comment')
link('TSOperator', 'Operator')
link('TSNumber', 'Number')
link('TSType', 'Type')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('TSTagDelimiter', 'Type')
link('TSNamespace', 'TSType')
