vim.cmd[[highlight clear]]
vim.g.colors_name = 'absent'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color7 = '#cf433e'
local Color0 = '#44515e'
local Color4 = '#228a96'
local Color11 = '#244b54'
local Color3 = '#6ba77f'
local Color5 = '#e6eaef'
local Color14 = '#2e363f'
local Color10 = '#aeb9c4'
local Color13 = '#8192a3'
local Color12 = '#505f6e'
local Color6 = '#664e4d'
local Color8 = '#ffffff'
local Color2 = '#61bcc6'
local Color1 = '#addbbc'
local Color9 = '#252c33'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color8, Color4, nil)
highlight('WildMenu', Color9, Color10, nil)
highlight('Pmenu', Color9, Color10, nil)
highlight('PmenuSel', Color10, nil, nil)
highlight('PmenuThumb', Color9, Color10, nil)
highlight('Normal', Color9, Color10, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color14, Color13, nil)
highlight('TabLineFill', Color14, Color13, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSFunction', 'Function')
link('TSNamespace', 'TSType')
link('TSOperator', 'Operator')
link('TSProperty', 'TSField')
link('Folded', 'Comment')
link('TSLabel', 'Type')
link('TSComment', 'Comment')
link('Repeat', 'Conditional')
link('TSKeyword', 'Keyword')
link('TSNumber', 'Number')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSFuncMacro', 'Macro')
link('TSParameter', 'Constant')
link('TSParameterReference', 'TSParameter')
link('TSConditional', 'Conditional')
link('Operator', 'Keyword')
link('Macro', 'Function')
link('TSTag', 'MyTag')
link('TSConstant', 'Constant')
link('TSField', 'Constant')
link('TelescopeNormal', 'Normal')
link('Conditional', 'Operator')
link('CursorLineNr', 'Identifier')
link('Whitespace', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSTagDelimiter', 'Type')
link('NonText', 'Comment')
link('TSString', 'String')
link('TSRepeat', 'Repeat')
link('TSType', 'Type')
link('TSPunctBracket', 'MyTag')
