-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color7 = '#18202c'
local Color5 = '#606a87'
local Color9 = '#1b1f32'
local Color10 = '#444b6f'
local Color2 = '#4758ad'
local Color6 = '#b8cdfe'
local Color8 = '#201725'
local Color0 = '#a5b3fe'
local Color1 = '#516aec'
local Color11 = '#7683a5'
local Color4 = '#131520'
local Color3 = '#33abcc'

highlight('String', nil, Color0, nil)
highlight('Number', nil, Color1, nil)
highlight('Comment', nil, Color2, 'italic')
highlight('Conditional', nil, Color3, 'italic')
highlight('Repeat', nil, Color3, 'italic')
highlight('StatusLine', Color5, Color4, nil)
highlight('WildMenu', Color4, Color6, nil)
highlight('Pmenu', Color4, Color6, nil)
highlight('PmenuSel', Color6, Color4, nil)
highlight('PmenuThumb', Color4, Color6, nil)
highlight('DiffAdd', Color7, nil, nil)
highlight('DiffDelete', Color8, nil, nil)
highlight('Normal', Color4, Color6, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color4, nil, nil)
highlight('LineNr', nil, Color10, nil)
highlight('TabLine', Color4, Color11, nil)
highlight('TabLineSel', Color6, Color4, nil)
highlight('TabLineFill', Color4, Color11, nil)
highlight('TSPunctDelimiter', nil, Color6, nil)

link('TSParameterReference', 'TSParameter')
link('TSFunction', 'Function')
link('TSNumber', 'Number')
link('Folded', 'Comment')
link('TSProperty', 'TSField')
link('TSNamespace', 'TSType')
link('TSField', 'Constant')
link('Conditional', 'Operator')
link('TSTagDelimiter', 'Type')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('CursorLineNr', 'Identifier')
link('TSConstant', 'Constant')
link('TSFuncMacro', 'Macro')
link('TSPunctBracket', 'MyTag')
link('Repeat', 'Conditional')
link('TSComment', 'Comment')
link('TSType', 'Type')
link('TelescopeNormal', 'Normal')
link('Macro', 'Function')
link('TSTag', 'MyTag')
link('TSLabel', 'Type')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Operator', 'Keyword')
link('Whitespace', 'Comment')
link('TSKeyword', 'Keyword')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('NonText', 'Comment')
link('TSString', 'String')
