-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]
vim.g.colors_name = 'ayu-light'

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#4cbf99'
local Color6 = '#ed9366'
local Color13 = '#d3e1f4'
local Color12 = '#f8e8eb'
local Color8 = '#e65050'
local Color7 = '#f2ae49'
local Color3 = '#a37acc'
local Color5 = '#fa8d3e'
local Color4 = '#5c6166'
local Color0 = '#abadb0'
local Color14 = '#cccfd3'
local Color10 = '#8a9199'
local Color9 = '#f8f9fa'
local Color11 = '#e6f1e3'
local Color1 = '#86b300'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Number', nil, Color3, nil)
highlight('Identifier', nil, Color4, nil)
highlight('Type', nil, Color5, nil)
highlight('Keyword', nil, Color5, nil)
highlight('Operator', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Error', nil, Color8, nil)
highlight('StatusLine', Color10, Color9, nil)
highlight('WildMenu', Color9, Color4, nil)
highlight('Pmenu', Color9, Color4, nil)
highlight('PmenuSel', Color4, Color9, nil)
highlight('PmenuThumb', Color9, Color4, nil)
highlight('DiffAdd', Color11, nil, nil)
highlight('DiffDelete', Color12, nil, nil)
highlight('Normal', Color9, Color4, nil)
highlight('Visual', Color13, nil, nil)
highlight('CursorLine', Color13, nil, nil)
highlight('ColorColumn', Color13, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color14, nil)
highlight('TabLine', Color9, Color10, nil)
highlight('TabLineSel', Color4, Color9, nil)
highlight('TabLineFill', Color9, Color10, nil)
highlight('TSPunctDelimiter', nil, Color4, nil)

link('TSFunction', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('TSField', 'Constant')
link('CursorLineNr', 'Identifier')
link('TSFloat', 'Number')
link('TelescopeNormal', 'Normal')
link('TSType', 'Type')
link('TSTagDelimiter', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSString', 'String')
link('TSConstant', 'Constant')
link('Macro', 'Function')
link('Conditional', 'Operator')
link('TSNamespace', 'TSType')
link('TSParameter', 'Constant')
link('TSKeyword', 'Keyword')
link('TSPunctBracket', 'MyTag')
link('TSComment', 'Comment')
link('TSNumber', 'Number')
link('TSProperty', 'TSField')
link('Whitespace', 'Comment')
link('Folded', 'Comment')
link('TSRepeat', 'Repeat')
link('Operator', 'Keyword')
link('NonText', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSOperator', 'Operator')
link('TSTag', 'MyTag')
