-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]
vim.g.colors_name = 'ayu-mirage-bordered'

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color1 = '#d5ff80'
local Color7 = '#ffd173'
local Color11 = '#242936'
local Color12 = '#303e3c'
local Color8 = '#ff6666'
local Color3 = '#dfbfff'
local Color14 = '#2b4668'
local Color15 = '#4c525d'
local Color13 = '#3d323f'
local Color9 = '#707a8c'
local Color6 = '#f29e74'
local Color4 = '#cccac2'
local Color2 = '#95e6cb'
local Color10 = '#1f2430'
local Color0 = '#6e7c8e'
local Color5 = '#ffad66'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Number', nil, Color3, nil)
highlight('Identifier', nil, Color4, nil)
highlight('Type', nil, Color5, nil)
highlight('Keyword', nil, Color5, nil)
highlight('Operator', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Error', nil, Color8, nil)
highlight('StatusLine', Color9, Color10, nil)
highlight('WildMenu', Color11, Color4, nil)
highlight('Pmenu', Color11, Color4, nil)
highlight('PmenuSel', Color4, Color11, nil)
highlight('PmenuThumb', Color11, Color4, nil)
highlight('DiffAdd', Color12, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color11, Color4, nil)
highlight('Visual', Color14, nil, nil)
highlight('CursorLine', Color14, nil, nil)
highlight('ColorColumn', Color14, nil, nil)
highlight('SignColumn', Color11, nil, nil)
highlight('LineNr', nil, Color15, nil)
highlight('TabLine', Color10, Color9, nil)
highlight('TabLineSel', Color4, Color11, nil)
highlight('TabLineFill', Color10, Color9, nil)
highlight('TSPunctDelimiter', nil, Color4, nil)

link('Macro', 'Function')
link('Folded', 'Comment')
link('Conditional', 'Operator')
link('TSOperator', 'Operator')
link('CursorLineNr', 'Identifier')
link('Whitespace', 'Comment')
link('TSFunction', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSConstant', 'Constant')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSField', 'Constant')
link('TSLabel', 'Type')
link('TSKeyword', 'Keyword')
link('Operator', 'Keyword')
link('TSProperty', 'TSField')
link('TSFuncMacro', 'Macro')
link('TSParameter', 'Constant')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSFloat', 'Number')
link('Repeat', 'Conditional')
link('TSParameterReference', 'TSParameter')
link('TSTag', 'MyTag')
link('NonText', 'Comment')
link('TSNumber', 'Number')
link('TelescopeNormal', 'Normal')
link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
link('TSRepeat', 'Repeat')
link('TSConditional', 'Conditional')
link('TSNamespace', 'TSType')
link('TSString', 'String')
link('TSType', 'Type')
