-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#fb7a6c'
local Color4 = '#edbc7f'
local Color3 = '#17d7d7'
local Color10 = '#f69662'
local Color15 = '#604240'
local Color0 = '#77b03e'
local Color6 = '#17d7c4'
local Color13 = '#2e2424'
local Color7 = '#69d293'
local Color16 = '#5d4242'
local Color8 = '#ad92ff'
local Color1 = '#8d6c6c'
local Color5 = '#d3b1b1'
local Color14 = '#473332'
local Color11 = '#9b8484'
local Color12 = '#281f1f'
local Color17 = '#f69c95'
local Color9 = '#f08390'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color11, Color12, nil)
highlight('WildMenu', Color13, Color5, nil)
highlight('Pmenu', Color13, Color5, nil)
highlight('PmenuSel', Color5, Color14, nil)
highlight('PmenuThumb', Color13, Color5, nil)
highlight('DiffAdd', Color13, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color13, Color5, nil)
highlight('Visual', Color15, nil, nil)
highlight('CursorLine', Color15, nil, nil)
highlight('ColorColumn', Color15, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color16, nil)
highlight('TabLine', Color12, Color16, nil)
highlight('TabLineSel', Color17, Color14, nil)
highlight('TabLineFill', Color12, Color16, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('Whitespace', 'Comment')
link('TSString', 'String')
link('TSLabel', 'Type')
link('TSConstant', 'Constant')
link('Folded', 'Comment')
link('NonText', 'Comment')
link('TSOperator', 'Operator')
link('TSNumber', 'Number')
link('TSField', 'Constant')
link('TSFloat', 'Number')
link('TSParameter', 'Constant')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSPunctBracket', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSFuncMacro', 'Macro')
link('TSFunction', 'Function')
link('TSTagDelimiter', 'Type')
link('TSConditional', 'Conditional')
link('TSParameterReference', 'TSParameter')
link('TSProperty', 'TSField')
link('TSRepeat', 'Repeat')
link('TSKeyword', 'Keyword')
link('Conditional', 'Operator')
link('Macro', 'Function')
link('TSComment', 'Comment')
link('Repeat', 'Conditional')
link('TSNamespace', 'TSType')
link('TSType', 'Type')
link('CursorLineNr', 'Identifier')
link('TelescopeNormal', 'Normal')
link('TSTag', 'MyTag')
link('Operator', 'Keyword')
