vim.cmd[[highlight clear]]
vim.g.colors_name = 'coffee-contrast'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#f5f3eb'
local Color12 = '#0d3d3b'
local Color4 = '#80b2b0'
local Color8 = '#0a9f9b'
local Color9 = '#ffffff'
local Color15 = '#1a1515'
local Color0 = '#423738'
local Color14 = '#806767'
local Color11 = '#c4babb'
local Color1 = '#a58163'
local Color5 = '#e77757'
local Color6 = '#664e4d'
local Color13 = '#483939'
local Color10 = '#0f0c0c'
local Color7 = '#cf433e'
local Color2 = '#cc8f5d'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color9, Color8, nil)
highlight('WildMenu', Color10, Color11, nil)
highlight('Pmenu', Color10, Color11, nil)
highlight('PmenuSel', Color11, nil, nil)
highlight('PmenuThumb', Color10, Color11, nil)
highlight('Normal', Color10, Color11, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color15, Color14, nil)
highlight('TabLineFill', Color15, Color14, nil)
highlight('TSPunctDelimiter', nil, Color11, nil)

link('TSComment', 'Comment')
link('TSType', 'Type')
link('TSNumber', 'Number')
link('TSFunction', 'Function')
link('TSFloat', 'Number')
link('Operator', 'Keyword')
link('NonText', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TelescopeNormal', 'Normal')
link('TSParameterReference', 'TSParameter')
link('TSParameter', 'Constant')
link('TSNamespace', 'TSType')
link('TSLabel', 'Type')
link('TSOperator', 'Operator')
link('TSTagDelimiter', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSRepeat', 'Repeat')
link('TSFuncMacro', 'Macro')
link('TSConditional', 'Conditional')
link('TSString', 'String')
link('Whitespace', 'Comment')
link('Macro', 'Function')
link('TSProperty', 'TSField')
link('TSTag', 'MyTag')
link('Conditional', 'Operator')
link('Repeat', 'Conditional')
link('TSKeyword', 'Keyword')
link('CursorLineNr', 'Identifier')
link('TSField', 'Constant')
link('Folded', 'Comment')
link('TSConstant', 'Constant')
