vim.cmd[[highlight clear]]
vim.g.colors_name = 'firefly-pro-bright'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#95e6cb'
local Color14 = '#252813'
local Color5 = '#827db5'
local Color11 = '#b3b8c5'
local Color12 = '#0a0a0a'
local Color3 = '#e6e600'
local Color13 = '#343434'
local Color0 = '#626a73'
local Color16 = '#474747'
local Color18 = '#a0a8bd'
local Color6 = '#ff6600'
local Color7 = '#ff8533'
local Color8 = '#ff0066'
local Color17 = '#4d5466'
local Color4 = '#a8aebd'
local Color10 = '#000000'
local Color1 = '#a4bd00'
local Color9 = '#787e8d'
local Color15 = '#2c1e18'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Number', nil, Color3, nil)
highlight('Identifier', nil, Color4, nil)
highlight('Type', nil, Color5, nil)
highlight('Keyword', nil, Color5, nil)
highlight('Operator', nil, Color6, nil)
highlight('Function', nil, Color7, nil)
highlight('Error', nil, Color8, nil)
highlight('StatusLine', Color9, Color10, nil)
highlight('WildMenu', Color12, Color11, nil)
highlight('Pmenu', Color12, Color11, nil)
highlight('PmenuSel', Color11, Color13, nil)
highlight('PmenuThumb', Color12, Color11, nil)
highlight('DiffAdd', Color14, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color12, Color11, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color12, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color10, Color18, nil)
highlight('TabLineSel', Color1, Color13, nil)
highlight('TabLineFill', Color10, Color18, nil)
highlight('TSPunctDelimiter', nil, Color11, nil)

link('TelescopeNormal', 'Normal')
link('TSLabel', 'Type')
link('TSTagDelimiter', 'Type')
link('TSFuncMacro', 'Macro')
link('TSParameter', 'Constant')
link('TSNumber', 'Number')
link('Folded', 'Comment')
link('TSConstant', 'Constant')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TSString', 'String')
link('NonText', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConditional', 'Conditional')
link('TSRepeat', 'Repeat')
link('TSProperty', 'TSField')
link('Whitespace', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSFloat', 'Number')
link('TSFunction', 'Function')
link('Macro', 'Function')
link('TSOperator', 'Operator')
link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameterReference', 'TSParameter')
link('Operator', 'Keyword')
link('TSType', 'Type')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('Repeat', 'Conditional')
