vim.cmd[[highlight clear]]
vim.g.colors_name = 'github'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color10 = '#666666'
local Color12 = '#3d3d3d'
local Color11 = '#999999'
local Color0 = '#555555'
local Color1 = '#e53d67'
local Color2 = '#66c4c4'
local Color4 = '#664e4d'
local Color7 = '#ffffff'
local Color5 = '#cf433e'
local Color3 = '#cccccc'
local Color6 = '#7385bc'
local Color8 = '#333333'
local Color9 = '#214c4c'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color1, nil)
highlight('Error', Color4, Color5, nil)
highlight('StatusLine', Color7, Color6, nil)
highlight('WildMenu', Color8, Color7, nil)
highlight('Pmenu', Color8, Color7, nil)
highlight('PmenuSel', Color7, nil, nil)
highlight('PmenuThumb', Color8, Color7, nil)
highlight('Normal', Color8, Color7, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color10, nil)
highlight('TabLine', Color12, Color11, nil)
highlight('TabLineFill', Color12, Color11, nil)
highlight('TSPunctDelimiter', nil, Color7, nil)

link('TSType', 'Type')
link('TSOperator', 'Operator')
link('TSLabel', 'Type')
link('TelescopeNormal', 'Normal')
link('TSPunctBracket', 'MyTag')
link('TSNumber', 'Number')
link('NonText', 'Comment')
link('TSFuncMacro', 'Macro')
link('Conditional', 'Operator')
link('TSNamespace', 'TSType')
link('Folded', 'Comment')
link('TSProperty', 'TSField')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSField', 'Constant')
link('TSFunction', 'Function')
link('TSKeyword', 'Keyword')
link('Repeat', 'Conditional')
link('TSString', 'String')
link('TSConstant', 'Constant')
link('TSParameterReference', 'TSParameter')
link('CursorLineNr', 'Identifier')
link('Whitespace', 'Comment')
link('TSComment', 'Comment')
link('TSParameter', 'Constant')
link('Macro', 'Function')
link('TSTagDelimiter', 'Type')
link('TSRepeat', 'Repeat')
link('Operator', 'Keyword')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSFloat', 'Number')
link('TSTag', 'MyTag')
