-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color6 = '#664e4d'
local Color1 = '#f36e3a'
local Color4 = '#a7dbd8'
local Color7 = '#cf433e'
local Color11 = '#0c0d0e'
local Color2 = '#f25619'
local Color13 = '#3b4045'
local Color0 = '#505c63'
local Color9 = '#ffffff'
local Color3 = '#fa6900'
local Color5 = '#69d2e7'
local Color12 = '#593519'
local Color14 = '#6a737c'
local Color15 = '#151719'
local Color8 = '#f38630'
local Color10 = '#f8f8f2'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color9, Color8, nil)
highlight('WildMenu', Color11, Color10, nil)
highlight('Pmenu', Color11, Color10, nil)
highlight('PmenuSel', Color10, nil, nil)
highlight('PmenuThumb', Color11, Color10, nil)
highlight('Normal', Color11, Color10, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color11, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color15, Color14, nil)
highlight('TabLineFill', Color15, Color14, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSParameterReference', 'TSParameter')
link('Whitespace', 'Comment')
link('Operator', 'Keyword')
link('TSField', 'Constant')
link('TSFuncMacro', 'Macro')
link('Macro', 'Function')
link('TSProperty', 'TSField')
link('TSFloat', 'Number')
link('TSFunction', 'Function')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSComment', 'Comment')
link('Repeat', 'Conditional')
link('TSNamespace', 'TSType')
link('TSPunctBracket', 'MyTag')
link('TSKeyword', 'Keyword')
link('TSType', 'Type')
link('TSConditional', 'Conditional')
link('NonText', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('TSTag', 'MyTag')
link('CursorLineNr', 'Identifier')
link('TSOperator', 'Operator')
link('TSString', 'String')
link('TSLabel', 'Type')
link('TSConstant', 'Constant')
link('Conditional', 'Operator')
link('TSTagDelimiter', 'Type')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('TSNumber', 'Number')
link('TelescopeNormal', 'Normal')
