vim.cmd[[highlight clear]]
vim.g.colors_name = 'hc-wonderland-wood'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color14 = '#3a3647'
local Color11 = '#8f8da6'
local Color0 = '#A4EF58'
local Color8 = '#9a94e9'
local Color10 = '#e4a792'
local Color12 = '#1b192f'
local Color7 = '#91d6a7'
local Color3 = '#92b4ff'
local Color16 = '#564f59'
local Color2 = '#ff7e70'
local Color1 = '#817f97'
local Color17 = '#57547e'
local Color5 = '#d6d5e3'
local Color15 = '#1f1d36'
local Color4 = '#fbe7c3'
local Color6 = '#7ddcbf'
local Color9 = '#ed98cb'
local Color13 = '#1F1D36'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color11, Color12, nil)
highlight('WildMenu', Color13, Color5, nil)
highlight('Pmenu', Color13, Color5, nil)
highlight('PmenuSel', Color5, Color14, nil)
highlight('PmenuThumb', Color13, Color5, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color13, Color5, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color12, Color17, nil)
highlight('TabLineSel', Color4, Color14, nil)
highlight('TabLineFill', Color12, Color17, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('TSString', 'String')
link('TSLabel', 'Type')
link('TSFuncMacro', 'Macro')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSKeyword', 'Keyword')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Macro', 'Function')
link('TSNamespace', 'TSType')
link('TSTag', 'MyTag')
link('Repeat', 'Conditional')
link('TSProperty', 'TSField')
link('TSField', 'Constant')
link('Conditional', 'Operator')
link('TSFloat', 'Number')
link('TSFunction', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSTagDelimiter', 'Type')
link('TSConstant', 'Constant')
link('TelescopeNormal', 'Normal')
link('TSType', 'Type')
link('Operator', 'Keyword')
link('Whitespace', 'Comment')
link('TSComment', 'Comment')
link('TSParameter', 'Constant')
link('TSParameterReference', 'TSParameter')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('NonText', 'Comment')
link('TSOperator', 'Operator')
