vim.cmd[[highlight clear]]
vim.g.colors_name = 'hyrule-light'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#93a594'
local Color14 = '#949290'
local Color4 = '#68912e'
local Color9 = '#c0d5c1'
local Color7 = '#b7950c'
local Color11 = '#aaca9e'
local Color2 = '#f5c504'
local Color3 = '#407710'
local Color5 = '#664e4d'
local Color13 = '#b4cdb5'
local Color10 = '#2d2c2b'
local Color1 = '#ce830d'
local Color12 = '#83ac85'
local Color8 = '#ffffff'
local Color6 = '#cf433e'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color4, nil)
highlight('Error', Color5, Color6, nil)
highlight('StatusLine', Color8, Color7, nil)
highlight('WildMenu', Color9, Color10, nil)
highlight('Pmenu', Color9, Color10, nil)
highlight('PmenuSel', Color10, nil, nil)
highlight('PmenuThumb', Color9, Color10, nil)
highlight('Normal', Color9, Color10, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color14, nil)
highlight('TabLineSel', Color10, nil, nil)
highlight('TabLineFill', Color13, Color14, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSTagDelimiter', 'Type')
link('TSNamespace', 'TSType')
link('TSOperator', 'Operator')
link('TSNumber', 'Number')
link('TSConditional', 'Conditional')
link('CursorLineNr', 'Identifier')
link('TSKeyword', 'Keyword')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSFuncMacro', 'Macro')
link('TSTag', 'MyTag')
link('TSFloat', 'Number')
link('Macro', 'Function')
link('NonText', 'Comment')
link('TSParameterReference', 'TSParameter')
link('Folded', 'Comment')
link('Whitespace', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSProperty', 'TSField')
link('Conditional', 'Operator')
link('TSFunction', 'Function')
link('Repeat', 'Conditional')
link('TSField', 'Constant')
link('TSType', 'Type')
link('TSPunctBracket', 'MyTag')
link('TSParameter', 'Constant')
link('TSConstant', 'Constant')
link('Operator', 'Keyword')
link('TSLabel', 'Type')
link('TSRepeat', 'Repeat')
link('TelescopeNormal', 'Normal')
link('TSComment', 'Comment')
link('TSString', 'String')
