vim.cmd[[highlight clear]]
vim.g.colors_name = 'laracasts-light'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color1 = '#98d5d6'
local Color2 = '#c68369'
local Color4 = '#00b1b3'
local Color9 = '#ccefef'
local Color7 = '#cf433e'
local Color11 = '#f5f5f5'
local Color10 = '#cccccc'
local Color5 = '#4d545d'
local Color8 = '#ffffff'
local Color12 = '#b5bac1'
local Color3 = '#ef6733'
local Color0 = '#9eacbc'
local Color6 = '#664e4d'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color8, Color4, nil)
highlight('WildMenu', Color8, Color5, nil)
highlight('Pmenu', Color8, Color5, nil)
highlight('PmenuSel', Color5, nil, nil)
highlight('PmenuThumb', Color8, Color5, nil)
highlight('Normal', Color8, Color5, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color8, nil, nil)
highlight('LineNr', nil, Color10, nil)
highlight('TabLine', Color11, Color12, nil)
highlight('TabLineSel', Color5, nil, nil)
highlight('TabLineFill', Color11, Color12, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('Macro', 'Function')
link('Folded', 'Comment')
link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSConditional', 'Conditional')
link('Operator', 'Keyword')
link('TSType', 'Type')
link('TelescopeNormal', 'Normal')
link('TSKeyword', 'Keyword')
link('TSFunction', 'Function')
link('Whitespace', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSTag', 'MyTag')
link('TSPunctBracket', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('Repeat', 'Conditional')
link('TSParameter', 'Constant')
link('TSLabel', 'Type')
link('TSFuncMacro', 'Macro')
link('NonText', 'Comment')
link('TSNumber', 'Number')
link('TSField', 'Constant')
link('TSString', 'String')
link('TSTagDelimiter', 'Type')
link('TSFloat', 'Number')
link('TSNamespace', 'TSType')
link('TSProperty', 'TSField')
link('CursorLineNr', 'Identifier')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('TSConstant', 'Constant')
