-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color5 = '#1a9d6b'
local Color2 = '#e4f279'
local Color1 = '#c5d671'
local Color12 = '#0e3d2f'
local Color15 = '#507396'
local Color13 = '#2c4054'
local Color9 = '#ffffff'
local Color10 = '#090d11'
local Color14 = '#10171e'
local Color0 = '#2c3f51'
local Color7 = '#cf433e'
local Color8 = '#249388'
local Color4 = '#246c82'
local Color3 = '#9ce878'
local Color11 = '#9cadbc'
local Color6 = '#664e4d'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color9, Color8, nil)
highlight('WildMenu', Color10, Color11, nil)
highlight('Pmenu', Color10, Color11, nil)
highlight('PmenuSel', Color11, nil, nil)
highlight('PmenuThumb', Color10, Color11, nil)
highlight('Normal', Color10, Color11, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color14, Color15, nil)
highlight('TabLineFill', Color14, Color15, nil)
highlight('TSPunctDelimiter', nil, Color11, nil)

link('CursorLineNr', 'Identifier')
link('TSType', 'Type')
link('TSNumber', 'Number')
link('Conditional', 'Operator')
link('TelescopeNormal', 'Normal')
link('TSString', 'String')
link('TSFuncMacro', 'Macro')
link('TSTagDelimiter', 'Type')
link('Operator', 'Keyword')
link('TSFloat', 'Number')
link('TSNamespace', 'TSType')
link('Folded', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Repeat', 'Conditional')
link('TSComment', 'Comment')
link('Macro', 'Function')
link('TSRepeat', 'Repeat')
link('TSOperator', 'Operator')
link('TSKeyword', 'Keyword')
link('TSParameterReference', 'TSParameter')
link('TSPunctBracket', 'MyTag')
link('TSLabel', 'Type')
link('TSTag', 'MyTag')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Whitespace', 'Comment')
link('TSParameter', 'Constant')
link('TSFunction', 'Function')
link('TSField', 'Constant')
link('TSProperty', 'TSField')
