vim.cmd[[highlight clear]]
vim.g.colors_name = 'otakon'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color14 = '#a79ba7'
local Color9 = '#f9f3f9'
local Color11 = '#655c6d'
local Color8 = '#b1a6ca'
local Color6 = '#cf433e'
local Color0 = '#6a6a84'
local Color12 = '#756775'
local Color4 = '#e484b2'
local Color7 = '#ffffff'
local Color13 = '#4a404a'
local Color3 = '#cacbdd'
local Color1 = '#9eb2d9'
local Color2 = '#f6e6eb'
local Color10 = '#3f373f'
local Color5 = '#664e4d'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color4, nil)
highlight('Error', Color5, Color6, nil)
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color10, Color9, nil)
highlight('Pmenu', Color10, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color10, Color9, nil)
highlight('Normal', Color10, Color9, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color14, nil)
highlight('TabLineFill', Color13, Color14, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSProperty', 'TSField')
link('TSRepeat', 'Repeat')
link('Whitespace', 'Comment')
link('TSType', 'Type')
link('Repeat', 'Conditional')
link('NonText', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSKeyword', 'Keyword')
link('TSFuncMacro', 'Macro')
link('TSFloat', 'Number')
link('Operator', 'Keyword')
link('TSLabel', 'Type')
link('TSTagDelimiter', 'Type')
link('TSComment', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Folded', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('Macro', 'Function')
link('Conditional', 'Operator')
link('TSNumber', 'Number')
link('TSPunctBracket', 'MyTag')
link('TSString', 'String')
link('TSField', 'Constant')
link('TSNamespace', 'TSType')
link('TSFunction', 'Function')
link('TSParameter', 'Constant')
link('TSTag', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('TSOperator', 'Operator')
