-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#aaaaaa'
local Color1 = '#f4d370'
local Color7 = '#ffffff'
local Color8 = '#333333'
local Color9 = '#f6e0d7'
local Color10 = '#cccccc'
local Color2 = '#d3643b'
local Color11 = '#999999'
local Color12 = '#f5f5f5'
local Color5 = '#664e4d'
local Color6 = '#cf433e'
local Color3 = '#94c7b6'
local Color4 = '#b2bca4'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color1, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Keyword', nil, Color3, nil)
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color4, nil)
highlight('Error', Color5, Color6, nil)
highlight('StatusLine', Color7, Color3, nil)
highlight('WildMenu', Color7, Color8, nil)
highlight('Pmenu', Color7, Color8, nil)
highlight('PmenuSel', Color8, nil, nil)
highlight('PmenuThumb', Color7, Color8, nil)
highlight('Normal', Color7, Color8, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color10, nil)
highlight('TabLine', Color12, Color11, nil)
highlight('TabLineSel', Color8, nil, nil)
highlight('TabLineFill', Color12, Color11, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSKeyword', 'Keyword')
link('Folded', 'Comment')
link('TSType', 'Type')
link('TSField', 'Constant')
link('TSTag', 'MyTag')
link('TSParameter', 'Constant')
link('TelescopeNormal', 'Normal')
link('TSLabel', 'Type')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Macro', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSRepeat', 'Repeat')
link('TSFuncMacro', 'Macro')
link('NonText', 'Comment')
link('TSProperty', 'TSField')
link('TSOperator', 'Operator')
link('TSNumber', 'Number')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('TSNamespace', 'TSType')
link('TSString', 'String')
link('TSFloat', 'Number')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Operator', 'Keyword')
link('Whitespace', 'Comment')
link('Conditional', 'Operator')
link('CursorLineNr', 'Identifier')
link('TSComment', 'Comment')
link('TSFunction', 'Function')
link('TSParameterReference', 'TSParameter')
link('TSTagDelimiter', 'Type')
link('Repeat', 'Conditional')
