-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color6 = '#664e4d'
local Color0 = '#8e8e70'
local Color11 = '#f0ccb1'
local Color4 = '#fe5f00'
local Color7 = '#cf433e'
local Color1 = '#fdb825'
local Color2 = '#fd9825'
local Color13 = '#b6a481'
local Color3 = '#988f2a'
local Color9 = '#443a27'
local Color5 = '#8e7547'
local Color12 = '#c9ba9c'
local Color10 = '#ede8de'
local Color8 = '#ffffff'
local Color14 = '#e6dfd1'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color8, Color4, nil)
highlight('WildMenu', Color10, Color9, nil)
highlight('Pmenu', Color10, Color9, nil)
highlight('PmenuSel', Color9, nil, nil)
highlight('PmenuThumb', Color10, Color9, nil)
highlight('Normal', Color10, Color9, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color14, Color13, nil)
highlight('TabLineSel', Color9, nil, nil)
highlight('TabLineFill', Color14, Color13, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSFunction', 'Function')
link('TSString', 'String')
link('TSNamespace', 'TSType')
link('Folded', 'Comment')
link('TSLabel', 'Type')
link('Whitespace', 'Comment')
link('TSProperty', 'TSField')
link('TSType', 'Type')
link('TSTagDelimiter', 'Type')
link('Conditional', 'Operator')
link('TSKeyword', 'Keyword')
link('TSConstant', 'Constant')
link('TSFloat', 'Number')
link('TSTag', 'MyTag')
link('TSConditional', 'Conditional')
link('Macro', 'Function')
link('TSNumber', 'Number')
link('TSComment', 'Comment')
link('TSParameterReference', 'TSParameter')
link('Operator', 'Keyword')
link('TSFuncMacro', 'Macro')
link('TSRepeat', 'Repeat')
link('NonText', 'Comment')
link('TSOperator', 'Operator')
link('TSPunctBracket', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TelescopeNormal', 'Normal')
link('TSField', 'Constant')
link('Repeat', 'Conditional')
link('CursorLineNr', 'Identifier')
link('TSParameter', 'Constant')
