vim.cmd[[highlight clear]]
vim.g.colors_name = 'solarflare-light'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#999999'
local Color7 = '#222222'
local Color11 = '#f5f5f5'
local Color1 = '#c6bb15'
local Color3 = '#664e4d'
local Color6 = '#d87627'
local Color8 = '#ffdbdc'
local Color5 = '#ffffff'
local Color10 = '#888888'
local Color4 = '#cf433e'
local Color9 = '#cccccc'
local Color2 = '#ff4e50'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color2, nil)
highlight('Keyword', nil, Color2, nil)
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color1, nil)
highlight('Error', Color3, Color4, nil)
highlight('StatusLine', Color5, Color6, nil)
highlight('WildMenu', Color5, Color7, nil)
highlight('Pmenu', Color5, Color7, nil)
highlight('PmenuSel', Color7, nil, nil)
highlight('PmenuThumb', Color5, Color7, nil)
highlight('Normal', Color5, Color7, nil)
highlight('Visual', Color8, nil, nil)
highlight('CursorLine', Color8, nil, nil)
highlight('ColorColumn', Color8, nil, nil)
highlight('SignColumn', Color5, nil, nil)
highlight('LineNr', nil, Color9, nil)
highlight('TabLine', Color11, Color10, nil)
highlight('TabLineSel', Color7, nil, nil)
highlight('TabLineFill', Color11, Color10, nil)
highlight('TSPunctDelimiter', nil, Color7, nil)

link('TSTagDelimiter', 'Type')
link('Conditional', 'Operator')
link('TSPunctBracket', 'MyTag')
link('NonText', 'Comment')
link('TSKeyword', 'Keyword')
link('TSOperator', 'Operator')
link('TSFloat', 'Number')
link('TelescopeNormal', 'Normal')
link('TSParameter', 'Constant')
link('TSString', 'String')
link('Macro', 'Function')
link('TSConstant', 'Constant')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Operator', 'Keyword')
link('TSTag', 'MyTag')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('CursorLineNr', 'Identifier')
link('TSProperty', 'TSField')
link('TSNamespace', 'TSType')
link('TSField', 'Constant')
link('Repeat', 'Conditional')
link('TSRepeat', 'Repeat')
link('TSConditional', 'Conditional')
link('TSLabel', 'Type')
link('TSFunction', 'Function')
link('Whitespace', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSType', 'Type')
link('TSComment', 'Comment')
link('Folded', 'Comment')
link('TSNumber', 'Number')
link('TSParameterReference', 'TSParameter')
