-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color9 = '#ffffff'
local Color14 = '#d2d4da'
local Color5 = '#c8d5b9'
local Color0 = '#c5cae5'
local Color2 = '#d8b436'
local Color1 = '#baa353'
local Color10 = '#666a7a'
local Color12 = '#cccccc'
local Color8 = '#68b0ab'
local Color3 = '#8fc0a9'
local Color4 = '#a5a08e'
local Color7 = '#cf433e'
local Color6 = '#664e4d'
local Color11 = '#e0efee'
local Color13 = '#f5f5f5'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color9, Color8, nil)
highlight('WildMenu', Color9, Color10, nil)
highlight('Pmenu', Color9, Color10, nil)
highlight('PmenuSel', Color10, nil, nil)
highlight('PmenuThumb', Color9, Color10, nil)
highlight('Normal', Color9, Color10, nil)
highlight('Visual', Color11, nil, nil)
highlight('CursorLine', Color11, nil, nil)
highlight('ColorColumn', Color11, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color12, nil)
highlight('TabLine', Color13, Color14, nil)
highlight('TabLineSel', Color10, nil, nil)
highlight('TabLineFill', Color13, Color14, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSComment', 'Comment')
link('Repeat', 'Conditional')
link('TSFunction', 'Function')
link('TSType', 'Type')
link('TelescopeNormal', 'Normal')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('TSRepeat', 'Repeat')
link('TSProperty', 'TSField')
link('TSTag', 'MyTag')
link('TSKeyword', 'Keyword')
link('TSConstant', 'Constant')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Macro', 'Function')
link('TSTagDelimiter', 'Type')
link('TSConditional', 'Conditional')
link('TSField', 'Constant')
link('Whitespace', 'Comment')
link('Conditional', 'Operator')
link('TSNumber', 'Number')
link('TSFloat', 'Number')
link('TSFuncMacro', 'Macro')
link('Folded', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSLabel', 'Type')
link('TSString', 'String')
link('TSPunctBracket', 'MyTag')
link('Operator', 'Keyword')
link('TSNamespace', 'TSType')
link('TSParameterReference', 'TSParameter')
link('NonText', 'Comment')
link('TSOperator', 'Operator')
