vim.cmd[[highlight clear]]
vim.g.colors_name = 'waste-contrast'
-- Colorscheme generated by https://github.com/arcticlimer/djanho

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#223a39'
local Color3 = '#bbd4be'
local Color11 = '#081011'
local Color4 = '#f7a8a5'
local Color14 = '#49939c'
local Color8 = '#43bdb2'
local Color13 = '#295156'
local Color7 = '#cf433e'
local Color10 = '#b1c7cc'
local Color15 = '#0f1d1f'
local Color12 = '#1b4946'
local Color2 = '#e4f279'
local Color5 = '#f9d6bc'
local Color6 = '#664e4d'
local Color1 = '#c5d671'
local Color9 = '#ffffff'

highlight('Comment', nil, Color0, nil)
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('TSCharacter', nil, Color3, nil)
highlight('Keyword', nil, Color4, nil)
highlight('Type', nil, Color3, nil)
highlight('Function', nil, Color5, nil)
highlight('Error', Color6, Color7, nil)
highlight('StatusLine', Color9, Color8, nil)
highlight('WildMenu', Color11, Color10, nil)
highlight('Pmenu', Color11, Color10, nil)
highlight('PmenuSel', Color10, nil, nil)
highlight('PmenuThumb', Color11, Color10, nil)
highlight('Normal', Color11, Color10, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color11, nil, nil)
highlight('LineNr', nil, Color13, nil)
highlight('TabLine', Color15, Color14, nil)
highlight('TabLineFill', Color15, Color14, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSConditional', 'Conditional')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameter', 'Constant')
link('TSFunction', 'Function')
link('Folded', 'Comment')
link('NonText', 'Comment')
link('TSLabel', 'Type')
link('TSPunctBracket', 'MyTag')
link('TelescopeNormal', 'Normal')
link('TSComment', 'Comment')
link('Whitespace', 'Comment')
link('Macro', 'Function')
link('TSType', 'Type')
link('TSRepeat', 'Repeat')
link('Repeat', 'Conditional')
link('TSString', 'String')
link('TSTagDelimiter', 'Type')
link('TSFuncMacro', 'Macro')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('CursorLineNr', 'Identifier')
link('Conditional', 'Operator')
link('TSKeyword', 'Keyword')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSProperty', 'TSField')
link('TSTag', 'MyTag')
link('TSOperator', 'Operator')
link('TSField', 'Constant')
link('TSParameterReference', 'TSParameter')
link('TSFloat', 'Number')
link('TSNamespace', 'TSType')
